// <auto-generated />
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(ProductContext))]
    partial class ProductContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Data.Models.Product", b =>
                {
                    b.Property<string>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("ProductID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = "1",
                            Brand = "Samsung",
                            Name = "Galaxy A70",
                            Price = 800.0,
                            Quantity = 5,
                            Weight = 200.0
                        },
                        new
                        {
                            ProductID = "2",
                            Brand = "Samsung",
                            Name = "Galaxy A50",
                            Price = 600.0,
                            Quantity = 10,
                            Weight = 190.0
                        },
                        new
                        {
                            ProductID = "3",
                            Brand = "Samsung",
                            Name = "Galaxy A5",
                            Price = 600.0,
                            Quantity = 9,
                            Weight = 190.0
                        },
                        new
                        {
                            ProductID = "4",
                            Brand = "Samsung",
                            Name = "Galaxy S7 ",
                            Price = 700.0,
                            Quantity = 10,
                            Weight = 205.0
                        },
                        new
                        {
                            ProductID = "5",
                            Brand = "Samsung",
                            Name = "Note 10",
                            Price = 1000.0,
                            Quantity = 5,
                            Weight = 180.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
